add link for group users
Andrii-Kozak/mark1 pull request #10
Opened 2021-02-15 13:20 UTC by Andrii-Kozak

![image](https://user-images.githubusercontent.com/46384633/107951606-4734ea00-6fa1-11eb-8d1e-33c8f1221017.png)
![image](https://user-images.githubusercontent.com/46384633/107951629-50be5200-6fa1-11eb-8d3c-95d80a01e626.png)

2021-02-16 13:37 UTC, pereslop approved these changes

2021-02-16 15:49 UTC, pereslop commented on app/views/groups/_follow_unfollow_buttons.html.slim
> +- if @group.user_groups.where(user_id: current_user.id).present?
if groups.users.include?(current_user)

2021-02-16 15:50 UTC, pereslop commented on app/views/groups/_follow_unfollow_buttons.html.slim
> +  = link_to 'unfollow', unfollow_group_path, class: 'btn btn-user'
method: delete, remote: true

2021-02-16 15:50 UTC, pereslop commented on app/views/groups/_follow_unfollow_buttons.html.slim
> +  = link_to 'follow', follow_group_path, class: 'btn btn-user'
method: post, remote: true

2021-02-16 15:51 UTC, pereslop commented on config/routes.rb
> +      get 'follow', to: 'groups#follow', as: :follow
post

2021-02-16 15:51 UTC, pereslop commented on config/routes.rb
> +      get 'unfollow', to: 'groups#unfollow', as: :unfollow
delete

2021-02-16 15:53 UTC, pereslop reviewed
t

2021-02-16 22:29 UTC, pereslop commented on app/views/groups/_follow_unfollow_buttons.html.slim
> +- if @group.users.include?(current_user)
Good

2021-02-16 22:30 UTC, pereslop commented on app/views/groups/show.html.slim
> +              - unless current_user == @user
What here wiil be @user?
You need te check only if current user is present

2021-02-16 22:30 UTC, pereslop commented on app/views/groups/show.html.slim
> +                = render 'groups/follow_unfollow_buttons'
Cover it in some div block

2021-02-16 22:32 UTC, pereslop commented on spec/controllers/groups_controller_spec.rb
> +    login_admin
Cover tasts which use it in describe block, and call it in before block

2021-02-16 22:32 UTC, pereslop commented on spec/controllers/groups_controller_spec.rb
> +  #   login_user
Before do
....
End

2021-02-17 14:46 UTC, pereslop commented on spec/controllers/groups_controller_spec.rb
> +          .to change(group.user_groups, :count).by(0)
better to check here http status 
https://relishapp.com/rspec/rspec-rails/v/3-0/docs/matchers/have-http-status-matcher

2021-02-17 16:28 UTC, pereslop commented on app/views/groups/show.html.slim
> +              - unless current_user == @user
unless current_user.persisted?

2021-02-18 08:02 UTC, f1nwe requested changes

2021-02-18 08:02 UTC, f1nwe commented on app/views/groups/show.html.slim
> +        .card.mt-3.p-2[style="min-height: 220px;"]
don't use inline styles.

2021-02-18 08:02 UTC, f1nwe commented on spec/controllers/groups_controller_spec.rb
> +          expect do
check also here http code.

2021-02-18 14:43 UTC, pereslop commented on app/views/groups/_user_members.html.slim
> +  - @group.users.order('id DESC').limit(4).each do |user|
`order('id DESC')` better to move to the User model scope

2021-02-19 09:20 UTC, pereslop commented on app/controllers/groups_controller.rb
> +    render 'groups/follow_btn'
do you need this line?

2021-02-19 15:15 UTC, pereslop commented on spec/models/user_spec.rb
> +    let!(:group) { FactoryBot.create(:group) }
i think this should be defined above the user_groups

2021-02-19 15:18 UTC, pereslop commented on spec/models/user_spec.rb
> +    let!(:user_group3) { FactoryBot.create(:user_group, user: user3, group: group, updated_at: 4.hours.ago) }
you don't need to create this varaibles, because you don't use them anywhere, better to move it in before block:
`
before do
  FactoryBot.create...
  FactoryBot.create...
  FactoryBot.create...
end
`

2021-02-19 15:33 UTC, pereslop commented on app/models/user.rb
> +  scope :by_joined_to_group, lambda { |group|
better name will be `by_joining_the_group`

2021-02-19 15:33 UTC, pereslop approved these changes

2021-02-19 15:35 UTC, pereslop commented on spec/models/application_record_spec.rb
> +      max_id = User.maximum('id')
if you sort them by created_at, I suppose you need to get maximum created_at

2021-02-19 15:36 UTC, pereslop commented on spec/models/application_record_spec.rb
> +      min_id = User.minimum('id')
the same as above

2021-02-19 15:36 UTC, pereslop commented on spec/models/application_record_spec.rb
> +    it 'sort collection by DESC id' do
rename

2021-02-19 15:37 UTC, pereslop commented on spec/models/application_record_spec.rb
> +      create_list(:user, 3)
better to create two users `user1, user2` with different created_at

2021-02-19 15:38 UTC, pereslop commented on spec/models/application_record_spec.rb
> +      min_id = User.minimum('id')
since you will specify created_at while defining users, you don't need those varaibles

2021-02-19 15:38 UTC, pereslop commented on spec/models/application_record_spec.rb
> +      expect(User.ordered_by_created_at.first).to eq(User.find(max_id))
to eq(user1)

2021-02-19 15:38 UTC, pereslop commented on spec/models/application_record_spec.rb
> +      expect(User.ordered_by_created_at.last).to eq(User.find(min_id))
to eq(user2)

2021-02-19 15:44 UTC, pereslop commented on spec/models/user_spec.rb
> +      expect(described_class.by_joined_to_group(group).last).to eq(user3)
you can add one more expect to check if collection contain exactly users that you created to that group before:
expect(described_class.by_joined_to_group(group).last).to eq([user1, user2, user3])
please read article : https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/contain-exactly-matcher

2021-02-19 17:18 UTC, Andrii-Kozak commented on app/controllers/groups_controller.rb
> +    render 'groups/follow_btn'
yes, because it doesn't work without it

2021-02-19 17:21 UTC, Andrii-Kozak commented on app/models/user.rb
> +  scope :by_joined_to_group, lambda { |group|
ok

2021-02-19 17:29 UTC, Andrii-Kozak commented on spec/models/user_spec.rb
> +    let!(:user_group3) { FactoryBot.create(:user_group, user: user3, group: group, updated_at: 4.hours.ago) }
done

2021-02-19 17:40 UTC, Andrii-Kozak commented on spec/models/application_record_spec.rb
> +      create_list(:user, 3)
ok

2021-02-19 17:53 UTC, Andrii-Kozak commented on spec/models/user_spec.rb
> +      expect(described_class.by_joined_to_group(group).last).to eq(user3)
ok
but it must be like
expect(described_class.by_joined_to_group(group)).to eq([user1, user2, user3])

2021-02-23 14:04 UTC, pereslop commented on app/controllers/groups/members_controller.rb
> +  before_action :authenticate_user!
do you need this really here? if yes can you tell me why?

2021-02-23 14:07 UTC, pereslop commented on app/models/application_record.rb
> +  scope :ordered_by_created_at, -> { order("created_at DESC") }
use single brackets for simple strings

2021-02-23 14:08 UTC, pereslop commented on app/models/user.rb
> +  scope :by_joining_the_group, lambda { |group|
please use `do....end` syntax for multiline blocks

2021-02-23 14:10 UTC, Andrii-Kozak commented on app/controllers/groups/members_controller.rb
> +  before_action :authenticate_user!
it's for unauthorized users that url are not available to

2021-02-23 14:11 UTC, pereslop commented on app/views/groups/show.html.slim
> +              - unless current_user == @user
again what is @user here?, current_user should be enough
`- if current_user.persisted
   = render ....
`

2021-02-23 14:11 UTC, pereslop commented on config/routes.rb
> +      delete 'remove_member', to: 'members#remove_member', as: :remove_member
good!!!!

2021-02-23 14:11 UTC, Andrii-Kozak commented on app/models/application_record.rb
> +  scope :ordered_by_created_at, -> { order("created_at DESC") }
ok

2021-02-23 14:12 UTC, pereslop commented on spec/controllers/groups/members_controller_spec.rb
> +  describe 'when group controller routes' do
Bad naming

2021-02-23 14:13 UTC, pereslop commented on spec/controllers/groups/members_controller_spec.rb
> +  context 'when user controller routes' do
what mean `when user controller routes`?

2021-02-23 14:14 UTC, pereslop commented on spec/controllers/groups/members_controller_spec.rb
> +  describe 'when group controller routes' do
in controller specs you should describe only actions 'GET#index', 'POST#create', ect.....

2021-02-23 14:15 UTC, pereslop commented on app/controllers/groups/members_controller.rb
> +  def remove_member
I cant find specs for this action ;)

2021-02-23 14:17 UTC, pereslop commented on spec/models/user_spec.rb
> +      expect(described_class.by_joining_the_group(group).last).to eq(user3)
please add one more expect, where you check the newest user from group

2021-02-23 14:18 UTC, pereslop approved these changes

2021-02-23 14:20 UTC, Andrii-Kozak commented on app/models/user.rb
> +  scope :by_joining_the_group, lambda { |group|
ok

2021-02-23 15:43 UTC, Andrii-Kozak commented on spec/controllers/groups/members_controller_spec.rb
> +  context 'when user controller routes' do
change to 'GET#index'

2021-02-23 15:44 UTC, Andrii-Kozak commented on spec/controllers/groups/members_controller_spec.rb
> +  describe 'when group controller routes' do
fixed

2021-02-23 18:41 UTC, Andrii-Kozak commented on app/views/groups/show.html.slim
> +              - unless current_user == @user
fixed)))

2021-02-23 18:43 UTC, Andrii-Kozak commented on app/controllers/groups/members_controller.rb
> +  def remove_member
![image](https://user-images.githubusercontent.com/46384633/108891752-c1a3e080-7617-11eb-8a4d-3ebac798151a.png)

2021-02-24 10:31 UTC, pereslop commented on spec/controllers/groups/members_controller_spec.rb
> +      expect { delete :remove_member, params: { group_id: group.id, member_id: user_remove.id } }
good

2021-02-24 13:04 UTC, merged