create post
Andrii-Kozak/mark1 pull request #13
Opened 2021-03-02 14:58 UTC by Andrii-Kozak

2021-03-03 20:24 UTC, pereslop commented on app/controllers/posts_controller.rb
> +      flash[:danger] = @post.errors.full_messages[0]
Why you fetch only finst element?

2021-03-03 20:24 UTC, pereslop commented on app/models/post.rb
> +  validates :body, presence: true, length: { minimum: 3, maximum: 100 }
Good

2021-03-03 20:26 UTC, pereslop commented on spec/controllers/users/posts_controller_spec.rb
> +      post :create, params: { user_id: user.id, post: new_post }
Bad, you create post above, and send it to cteate new one with sa same parameters

2021-03-03 20:32 UTC, Andrii-Kozak commented on app/controllers/posts_controller.rb
> +      flash[:danger] = @post.errors.full_messages[0]
Because I don't need an array of all errors messages, and for this I made screenshots that demonstrate everything

2021-03-03 20:41 UTC, pereslop commented on app/controllers/posts_controller.rb
> +      flash[:danger] = @post.errors.full_messages[0]
@post.errors.full_messages.join(', ')

2021-03-03 20:42 UTC, pereslop commented on app/controllers/posts_controller.rb
> +      flash[:danger] = @post.errors.full_messages[0]
i think you can have here two messages, that cant be blank, and cant be less than 3 symbols

2021-03-03 20:42 UTC, pereslop commented on spec/controllers/groups/posts_controller_spec.rb
> +    let(:new_post) { create(:post, body: "Something", postable: group, creator: user) }
let(:valid_params) { { body: "Something", postable: group, creator: user) } }

2021-03-03 20:43 UTC, pereslop commented on spec/controllers/groups/posts_controller_spec.rb
> +    let(:invalid_post) { '' }
let(:invalid_params) { {} }
    let(:invalid_params) { { body: 'aa' } }

2021-03-03 20:44 UTC, pereslop commented on spec/controllers/groups/posts_controller_spec.rb
> +        post :create, params: { group_id: group.id, post: new_post }
post :create, params: { group_id: group.id, post: valid params }

2021-03-03 20:45 UTC, pereslop commented on spec/controllers/groups/posts_controller_spec.rb
> +    it 'Post#create' do
```
describe 'Post#create do
 context 'when params is valid' do
  it 'creates new post' do
  end
 end
 context 'when params is invalid' do
  it 'does not create new post' do
  end
 end
```
end

2021-03-03 20:46 UTC, pereslop commented on spec/controllers/groups/posts_controller_spec.rb
> +    it 'Post#create' do
you should apply  that structure to controller action tests

2021-03-03 20:47 UTC, pereslop commented on spec/controllers/users/posts_controller_spec.rb
> +RSpec.describe Users::PostsController, type: :controller do
please look structure and comments in Groups::PostController :)

2021-03-03 20:47 UTC, pereslop reviewed
please fix comments

2021-03-04 13:33 UTC, Andrii-Kozak commented on spec/controllers/users/posts_controller_spec.rb
> +RSpec.describe Users::PostsController, type: :controller do
done!

2021-03-04 13:44 UTC, pereslop commented on spec/rails_helper.rb
> +Dir[Rails.root.join('spec/support/**/*.rb')].sort.each { |f| require f }
why you add sort here?

2021-03-04 13:44 UTC, pereslop commented on app/models/post.rb
> +  validates :body, presence: true, length: { minimum: 3, maximum: 100 }
but you need add specs to checks this validation

2021-03-04 13:45 UTC, pereslop commented on app/controllers/posts_controller.rb
> +      flash[:danger] = @post.errors.full_messages[0]
maybe better to add a comment 'why?´ instead of smile?

2021-03-04 13:46 UTC, pereslop commented on app/controllers/posts_controller.rb
> +      flash[:danger] = @post.errors.full_messages[0]
what if you add more validations, you will still show only first message?

2021-03-04 13:47 UTC, Andrii-Kozak commented on spec/rails_helper.rb
> +Dir[Rails.root.join('spec/support/**/*.rb')].sort.each { |f| require f }
it actually did rubocop with autocorect

2021-03-04 14:15 UTC, Andrii-Kozak commented on app/controllers/posts_controller.rb
> +      flash[:danger] = @post.errors.full_messages[0]
<@post.errors.full_messages.join(', ')> in this case work fine, but it give for us all messages.
in case <@post.errors.full_messages[0]>  we have the exact error message.

2021-03-04 14:22 UTC, Andrii-Kozak commented on app/models/post.rb
> +  validates :body, presence: true, length: { minimum: 3, maximum: 100 }
ok i will do this tomorrow!

2021-03-04 14:30 UTC, Andrii-Kozak commented on app/controllers/posts_controller.rb
> +      flash[:danger] = @post.errors.full_messages[0]
Ok, I will do as you say, because I respect you!
and also you have more experience as a developer!

2021-03-05 09:48 UTC, f1nwe requested changes

2021-03-05 09:48 UTC, f1nwe commented on app/controllers/groups_controller.rb
>      @group.destroy
please, use the bang version for `@group.destroy` when you're not checking the result of the destroy operation.

I mean, you can use `destroy` when doing something like
`if @group.destroy
   do_smt
end`
if not it is better to use `destroy!` to be sure that the record is deleted

2021-03-05 09:48 UTC, f1nwe commented on app/controllers/groups_controller.rb
>      flash[:warning] = "Group \"#{@group.group_name}\" has been deleted"
you have to set `flash` before `redirect_to groups_path`

2021-03-05 09:48 UTC, f1nwe commented on app/controllers/posts_controller.rb
> +    @post.creator = current_user
you can do it in one line:
`@post = @postable.posts.build(creator: creator, **post_params)`

2021-03-05 09:48 UTC, f1nwe commented on app/controllers/users/posts_controller.rb
> +  def redirect_to_postable
you're not using this method anywhere, remove that.
And naming is bad, 
`redirect_to_postable` is not redirecting anywhere, it should be called `render_postable`

2021-03-05 09:48 UTC, f1nwe commented on spec/controllers/groups/posts_controller_spec.rb
> +  describe 'Post#Сreate' do
this is not following style guides:
HTTP method should be uppercased, and method names just downcased.
`describe 'POST #create`

2021-03-05 09:48 UTC, f1nwe commented on spec/controllers/groups/posts_controller_spec.rb
> +      let(:valid_parameters) { { body: 'Something' } }
it is better use FactoryBot for generation valid attributes:
`attributes_for(:post).slice(:body)`

2021-03-05 09:48 UTC, f1nwe commented on spec/controllers/groups/posts_controller_spec.rb
> +      end
you can merge those two specs into one it will work two times faster

```suggestion
      it 'creates new post' do
        expect do
          post :create, params: { group_id: group.id, post: valid_parameters }
        end.to change(Post, :count).by(1)
        expect(group.posts.last.body).to eq(valid_parameters[:body])
        expect(response).to have_http_status(:redirect)
      end
```

2021-03-05 09:48 UTC, f1nwe commented on spec/controllers/groups/posts_controller_spec.rb
> +        end.to change(Post, :count).by(0)
`not_to change(Post, :count)` looks better

2021-03-05 09:48 UTC, f1nwe commented on spec/controllers/users/posts_controller_spec.rb
> +  describe 'Post#Сreate' do
style described above

2021-03-05 09:48 UTC, f1nwe commented on spec/controllers/users/posts_controller_spec.rb
> +      let(:valid_parameters) { { body: 'Something' } }
use factory

2021-03-05 09:48 UTC, f1nwe commented on spec/controllers/users/posts_controller_spec.rb
> +        end.to change(Post, :count).by(1)
merge those two examples to one

2021-03-05 09:48 UTC, f1nwe commented on spec/controllers/users/posts_controller_spec.rb
> +        end.to change(Post, :count).by(0)
`not_to change(Post, :count)`

2021-03-05 09:48 UTC, f1nwe commented on spec/controllers/users/posts_controller_spec.rb
> +  describe 'Post#Сreate' do
those specs are the same as in spec/controllers/groups/posts_controller_spec.rb
you can use `shared_examples` not to duplicate code.
You can rewrite it if you've done it before, if no - then just leave it as it.

2021-03-05 10:00 UTC, f1nwe commented on app/controllers/posts_controller.rb
> +      flash[:danger] = @post.errors.full_messages[0]
<facepalm>

2021-03-05 13:41 UTC, Andrii-Kozak commented on app/controllers/groups_controller.rb
>      flash[:warning] = "Group \"#{@group.group_name}\" has been deleted"
that is my bad)

2021-03-05 13:56 UTC, Andrii-Kozak commented on app/controllers/groups_controller.rb
>      @group.destroy
ok

2021-03-05 14:03 UTC, Andrii-Kozak commented on app/controllers/posts_controller.rb
> +    @post.creator = current_user
ok, but it's better to me for understanding

2021-03-07 15:37 UTC, merged