add group controller, and some style
Andrii-Kozak/mark1 pull request #4
Opened 2021-01-19 21:44 UTC by Andrii-Kozak

2021-01-20 11:08 UTC, pereslop commented on app/controllers/groups_controller.rb
> +    @group.save
what if group will not save? will be good to show some flash message with errors

2021-01-20 11:09 UTC, pereslop commented on app/controllers/groups_controller.rb
> +    @group.save
try to create group with to long name

2021-01-20 11:09 UTC, pereslop commented on app/controllers/groups_controller.rb
> +      render 'edit', warning: 'Invalid parameters for editing'
the same as cretae, you should show error messages

2021-01-20 11:10 UTC, pereslop commented on app/controllers/groups_controller.rb
> +    @group.destroy
the same, error messages

2021-01-20 14:13 UTC, pereslop commented on app/views/groups/new.html.slim
> +== render 'form'
what means `==`?

2021-01-20 14:14 UTC, pereslop commented on app/views/groups/show.html.slim
> +            strong = "#{@group.group_name}"
do you really need interpolation here?

2021-01-20 14:14 UTC, pereslop commented on app/views/groups/show.html.slim
> +            span = "#{@group.group_type}"
look comment above

2021-01-20 14:14 UTC, pereslop commented on app/views/groups/show.html.slim
> +            = "#{@group.description}"
look comment above

2021-01-20 14:15 UTC, pereslop commented on spec/controllers/groups_controller_spec.rb
> +# require 'rails_helper'
why specs is empty?

2021-01-20 14:16 UTC, mmarusyk commented on app/views/groups/show.html.slim
> +            strong = "#{@group.group_name}"
```suggestion
            strong
              = @group.group_name
```
Here and other templates

2021-01-20 14:16 UTC, mmarusyk commented on spec/controllers/groups_controller_spec.rb
> +# require 'rails_helper'
Add tests, pls. It's important

2021-01-20 14:16 UTC, mmarusyk commented on app/views/groups/show.html.slim
> +            strong = "#{@group.group_name}"
Add tests for controller

2021-01-20 14:16 UTC, pereslop commented on db/seeds.rb
> +FactoryBot.create_list(:group, 10)
aslo i think you need to create UserGroups, to crate related Users -> Groups

2021-01-20 14:18 UTC, pereslop reviewed
please add specs to GroupsController, and update seeds

2021-01-20 18:41 UTC, Andrii-Kozak commented on app/views/groups/new.html.slim
> +== render 'form'
it's not ready

2021-01-20 18:42 UTC, Andrii-Kozak commented on app/views/groups/show.html.slim
> +            strong = "#{@group.group_name}"
Yes of course

2021-01-20 19:20 UTC, pereslop commented on app/views/groups/new.html.slim
> +== render 'form'
==

2021-01-21 15:14 UTC, pereslop commented on spec/controllers/groups_controller_spec.rb
> +      get :show, params: { id: group.id }
also need test where you try to get group with non persisted ID
      get :show, params: { id: 65S4654 }

2021-01-21 15:14 UTC, pereslop commented on spec/controllers/groups_controller_spec.rb
> +          post :create, params: { group: valid_params }
add test where you send invalid params

2021-01-21 15:17 UTC, pereslop commented on spec/controllers/groups_controller_spec.rb
> +    it 'destroys the group and redirects to index' do
one more test where you try destroy with non pesisted id
`delete :destroy, params: { id: 654654 } `

2021-01-21 15:17 UTC, pereslop approved these changes

2021-01-21 16:03 UTC, Andrii-Kozak commented on spec/controllers/groups_controller_spec.rb
> +      get :show, params: { id: group.id }
done

2021-01-21 21:40 UTC, f1nwe requested changes

2021-01-21 21:40 UTC, f1nwe commented on app/controllers/application_controller.rb
> +    head :not_found, status: :not_found
implement 404 page instead of rendering empty body, or, at least `render plain: 'not found', staus: :not_found`

2021-01-21 21:40 UTC, f1nwe commented on app/controllers/application_controller.rb
>    protected
why did you use protected here? I almost sure that you have to use `private` here

2021-01-21 21:40 UTC, f1nwe commented on app/controllers/groups_controller.rb
> +    @groups = Group.page params[:page]
what would be here if the `params[:page]` is nil?
BTW prefer to always use parenthesis, it makes code much readable.

2021-01-21 21:40 UTC, f1nwe commented on app/controllers/groups_controller.rb
> +  def edit; end
You need to  find the model here and write it to an instance variable

2021-01-21 21:40 UTC, f1nwe commented on app/controllers/groups_controller.rb
> +  def edit; end
oh, I see. You're defining it in the callback. Hate this, but this is Rails way, ignore the comment above.

2021-01-21 21:40 UTC, f1nwe commented on app/controllers/groups_controller.rb
> +    if @group.destroy
Is there a case, when the group can't be removed?

2021-01-21 21:40 UTC, f1nwe commented on app/controllers/groups_controller.rb
> +      flash[:warning] = "Group \"#{@group.group_name}\" has been deleted"
Also currently anybody is able to remove or update the group, am I right?

2021-01-21 21:40 UTC, f1nwe commented on app/javascript/stylesheets/custom.scss
> +.list-inline-item ~ .list-inline-item {
strange selector.

2021-01-21 21:40 UTC, f1nwe commented on app/views/groups/_form.html.slim
> +            h3
Prefer to write in one line `h3 Edit Group` it will work =)

2021-01-21 21:40 UTC, f1nwe commented on app/views/groups/_form.html.slim
> +            form
` = simple_form_for ` generates form tag, here you have another one. Are you sure that you want to have nested forms?

2021-01-21 21:40 UTC, f1nwe commented on app/views/groups/_form.html.slim
> +                .input-group-prepend
Actually, I see that you have a lot of bootstrap classes here.
There is an ability in `simple_form` to generate form templates with bootstrap classes and don't have so much of boilerplate code. Check it out https://github.com/heartcombo/simple_form#bootstrap

2021-01-21 21:40 UTC, f1nwe commented on app/views/groups/_group.html.slim
> +        - if current_user.admin?
this block is empty. remove this or fix thee indentation.

2021-01-21 21:40 UTC, f1nwe commented on app/views/users/_user.html.slim
> +              strong = user.full_name
by convention, you should put the space between the tag and `=`

I mean `strong= user.full_name` instead of `strong = user.full_name` - this is NOT assigning to the variable.

2021-01-21 21:40 UTC, f1nwe commented on spec/controllers/groups_controller_spec.rb
> +  let!(:invalid_params) { { group_name: '' } }
you don't need `let!` here, and in most places too. Read about differences and change to `let` in proper places.

2021-01-21 21:40 UTC, f1nwe commented on spec/controllers/groups_controller_spec.rb
> +      get :index
is this page should be accessible for non-registered users?
if not - add specs and fix the problem in the controller too.
think about shared_examples for controller authenticationn

2021-01-21 21:40 UTC, f1nwe commented on spec/controllers/groups_controller_spec.rb
> +      get :show, params: { id: group.id }
You're making a request for the first time, this is ok

2021-01-21 21:40 UTC, f1nwe commented on spec/controllers/groups_controller_spec.rb
> +        get :show, params: { id: Group.last.id + 1 }
Here you're making a second request for each spec in the context, I am sure that you don't need this.
It will have bad performance and can break the specs.

2021-01-21 21:40 UTC, f1nwe commented on spec/controllers/groups_controller_spec.rb
> +  let!(:valid_params) { attributes_for :group }
this is not a global variable, please put it in appropriate contexts. You're using it only in the update and create actions, you should place them in there.

2021-01-21 21:40 UTC, f1nwe commented on spec/controllers/groups_controller_spec.rb
> +                               group: valid_params.merge!(group_name: 'Example',
wow, you're mutating variable here, are you sure that you want to do so?
Actually, are there other keys in valid_params hash except 'group_name, description, and group_type'?

2021-01-21 21:40 UTC, f1nwe commented on spec/controllers/groups_controller_spec.rb
> +          put :update, params: { id: group.id, group: invalid_params }
request #1

2021-01-21 21:40 UTC, f1nwe commented on spec/controllers/groups_controller_spec.rb
> +          put :update, params: { id: group.id, group: invalid_params }
request #2 - BAD!
You should make only on request to the controller per spec example!

2021-01-22 09:07 UTC, pereslop commented on spec/controllers/groups_controller_spec.rb
> +          put :update, params: { id: group.id, group: invalid_params }
if you want to to check if user is not updated, you don't need to check group_name, description, etc....
I think enough to check 'updated_at' column

2021-01-22 09:11 UTC, pereslop commented on spec/controllers/groups_controller_spec.rb
> +      get :index
he will implement access to pages in next stories, now this is not in scope of this task

2021-01-22 09:17 UTC, pereslop commented on app/javascript/stylesheets/custom.scss
> +.list-inline-item ~ .list-inline-item {
I am not sure if you what you want to do here, but if you want to apply style to last `.list-inline-item` element, please read about :`last-child` selector, maybe better to use that one

2021-01-22 14:10 UTC, merged